#
# Macro file for "AmBe.cc"
#
/tracking/verbose 0
/control/verbose 0
/run/verbose 0
#
##/testhadr/det/setAbsorMat BeO
##/testhadr/det/setContMat Stainless-Steel
##/testhadr/det/setAbsorRadius 15 mm
##/testhadr/det/setAbsorLength 60 mm
##/testhadr/det/setContThick  2.4 mm
#
/run/initialize
#
/process/list
#
#/gun/particle neutron
#/gun/ion 95 241
#/gun/energy 25 meV
#/gun/number 6000
#
/analysis/setFileName myresult
/analysis/h1/set 1 200  0. 2.  MeV # E_deposit from All in DrfitGap
/analysis/h1/set 2 200  0. 2.  MeV # E_deposit from alpha in DriftGap
/analysis/h1/set 3 300  0. 3.  MeV # E_deposit from gamma in DriftGap
/analysis/h1/set 4 300  0. 1.  MeV # E_deposit from e+- in DriftGap
/analysis/h1/set 5 300  0. 3.  MeV # energy spectrum of emerging alpha
/analysis/h1/set 6 300  0. 3.  MeV # energy spectrum of emerging gamma
/analysis/h1/set 7 300  0. 3.  MeV # energy spectrum of emerging secondary gamma
/analysis/h1/set 8 300  0. 3.  MeV # energy spectrum of emerging third gamma
/analysis/h1/set 9 300  0. 1   MeV # E spectrum of e-
/analysis/h1/set 10 300  0. 3. MeV # E_kin of alphas at entring DriftGap from Boron_pre
/analysis/h1/set 11 300  0. 3. MeV # E_kin of alphas at entring DriftGap from Boron_post
/analysis/h1/set 12 300  -1. 0. mm # number of captured neutron
/analysis/h1/set 13 300  0. 10. mm # drift length of alpha 
/analysis/h1/set 14 300  0. 3. MeV # E spectrum of e+

/analysis/h2/setX 0 100 -100 100 mm
/analysis/h2/setY 0 100 -100 100 mm

/analysis/h2/setX 1 200 -100 100 mm
/analysis/h2/setY 1 200 -100 100 mm

/analysis/h2/setX 2 200 -100 100 mm
/analysis/h2/setY 2 200 -10 1 mm

/analysis/h2/setX 3 200 -100 100 mm
/analysis/h2/setY 3 200 -10 1 mm

/analysis/h2/setX 4 500 -1 0 mm
/analysis/h2/setY 4 500 0 50 meV

/analysis/h2/setX 5 500 -1 0 mm
/analysis/h2/setY 5 500 0 3 MeV
#
/run/printProgress 100000
#
/run/beamOn 1000000
