#
# Macro file for "AmBe.cc"
#
/run/verbose 0
/tracking/verbose 2
/control/verbose 0

/analysis/ntuple/setActivationToAll true
#
##/testhadr/det/setAbsorMat BeO
##/testhadr/det/setContMat Stainless-Steel
##/testhadr/det/setAbsorRadius 15 mm
##/testhadr/det/setAbsorLength 60 mm
##/testhadr/det/setContThick  2.4 mm
#
/run/initialize
/run/numberOfThreads 1
#
#
#/gun/particle neutron
#/gun/ion 95 241
#/gun/energy 25 meV
#/gun/number 6000
/run/printProgress 10
#
/run/beamOn 10
